### ISSUE TITLE
[Story] As a user I must receive a successful payment email notification.

### ISSUE THREAD

**Issue by ryansagot** [unikbase/mv-stripe#1]
<table dir="ltr" style="height: 538px;" border="1" cellspacing="0" cellpadding="0"><colgroup><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /></colgroup>
<tbody>
<tr><td><b/>
Goal/Request
 </td>
<td>
User must receive an email after successful payment through Stripe. Email content must vary based on the Profile Language.

https://www.notion.so/unikbase/Emails-Payment-stripe-35c8659b06f54eb19868609061921296
</td></tr>
<tr><td><b/>
Acceptance Criteria
 </td>
<td>

- As a user I must receive an email after successful payment through Stripe.
- As a user I must receive the email in a language of my Profile Settings.

ENGLISH: 
Email Subject/Title: Your payment to Unikbase has been successfully completed
Email Content:
[unikbase logo]

Congratulations! Your payment has been successfully completed. Thank you for your trust and your purchase.

Your order has been received and will be processed as soon as possible. You will receive a confirmation email when your digital duplicate is ready.

In the meantime, we invite you to download the Unikbase application on your phone which will be used to store your digital duplicate.

We are at your disposal,

The Unikbase team

[app store and google play store logos to download our app]
[Unikbase UU logotype]
+ Unikbase, 320 rue Saint-Honoré 75001 Paris, France 
Contact [[hello@unikbase.com](mailto:hello@unikbase.com)](mailto:hello@unikbase.com)

FRENCH:
Email Subject/Title: Votre paiement auprès d’Unikbase a été effectué avec succès
Email Content:
[unikbase logo]

Félicitations ! Votre paiement a été effectué avec succès. Nous vous remercions de votre confiance et de votre achat.

Votre commande a été reçue et sera traitée dans les plus brefs délais. Vous recevrez un email de confirmation lorsque votre double numérique sera prêt.

D’ici là nous vous invitons dès à présent à télécharger sur votre téléphone l’application Unikbase qui servira à stocker votre double numérique. 

Nous restons à votre disposition,

L’équipe Unikbase

[app store and google play store logos to download our app]
[Unikbase UU logotype]'
+ Unikbase, 320 rue Saint-Honoré 75001 Paris, France 
Contact [[hello@unikbase.com](mailto:hello@unikbase.com)](mailto:hello@unikbase.com)

</td></tr>

</tbody>
</table>

**Comment by fmunir1086** [comment]
timespent*07:00 January 25, 2023

**Comment by fmunir1153** [comment]
timespent*03:48 January 26, 2023

Removed redundant logic for getting checkoutInfoUUId and replaced with mapped object to get that info and also Customer Email from stripe response
 - Added sending Failure email logic for failure cases and unit tested that its working fine.
 - Tommorrow I will use locales to switch via French/English emails, do code clean up for endpoints and functions and will add images in email.

**Comment by fmunir1153** [comment]
timespent*05:01 January 26, 2023

**Comment by fmunir1086** [comment]
timespent*01:30 January 28, 2023

- Working on setting logo images, but confused where we need to setup images in mv-stripe, might need an advice where to save images for mv-stripe module which will be referred to set as inline images in email.

**Comment by fmunir1086** [comment]
timespent*03:04 January 28, 2023

Worked with Shehryar for integrating cancel stripe payment on pressing back button. Still working on it because session we are trying to retrieve from stripe api is expired looks like there is some trick we donot know why this happening.

**Comment by fmunir1086** [comment]
timespent*04:09 January 30, 2023

Comitted all changes on repo and updated preprod for mv-stripe and tested it worked fine after configuring with new test account and new api key

**Comment by fmunir1086** [comment]
timespent*00:25 January 31, 2023

Communication/Collaboration with team over skype reading chat etc

**Comment by fmunir1086** [comment]
timespent*03:44 January 31, 2023

- Deployed mv-stripe on Production and set all necesarry stuff for production associated stripe.com account.
- Verified that on Success checkout record is updated by our webhook and email is sent, not sure email is not received, verified all email configuration settings and matched wih dev environment, despite all is same.
- Modified on dev checkout script to accept price_id as a new optional parameter for price tag from client side and verified its working with different prices I made for dev account.
- Comitted all changes on repo.

**Comment by fmunir1086** [comment]
timespent*03:14 January 31, 2023

 - 0 price_id only sends success email, no stripe checkout happens for such call, verified on dev
 - Comitted all changes to preprod and prod environments and updated api keys and price_id maps within scripts
 - Added a separate endpoint to send email only, if price_id is "0"
 - Email on production is not sent verified settings of prod with dev (where email is sent ), seems no issue and nothing in logs as well, will fix this later today.

**Comment by fmunir1086** [comment]
timespent*02:30 February 02, 2023

- Coordinated with Sebastian for remaining issue in email and other stuff 
- Coordinated with Rambu and set timiings, as he ended today  communicated him two changes, but will work with him tomorrow as it involves changing in cancel webhook also on stripe.com
- Just decided what is needed to be done for successful payment hooks execution

**Comment by fmunir1086** [comment]
timespent*03:10 February 02, 2023

- Tried email on wallet.unikbase.dev by using a simple email test and it worked, but on success payment stripe case email not sent, issue is with success payment hook, as account is linked with k8s.unikbase.dev success payment hook, which cannot retreive said session, will sit with Sebastian tomorrow to configure that one
 -  Added price tag information on metadata to have that in any case within session, will commit stuff when got success with email stuff, as done coding but right now comented for images, will test tomorrow 
 -  Reviewed facebook social networking login for keycloak, seems to be acievable, plan to start work on it tomorrow .

**Comment by fmunir1086** [comment]
timespent*05:00 February 03, 2023

- Full coordination and worked with Rambu to have a complete flow as discussed with Sebastian for Stripe checkout and success and payment cases
- Made changes on meveo side to adjust no email from on boarding screen, handled few error cases for success and failure payment hooks from our side, made zero payment call successful for just sending email for now and fetched customer email form stripe session under customerDetails field of session  
- Tested all stuff after changes ondev, committed changes to repository and updated module on Live environment and verified after changes done by Sebastian, only payment failure case form stripe is not tested, donot know how to test it.

**Comment by fmunir1086** [comment]
timespent*03:40 February 03, 2023

Researched on setting inline images on Email, looks like we cannot set SVG and its explainable, we might need png or jpg of same icons and email will attach inline images and that Git hub issue will be resolved.

**Comment by fmunir1153** [comment]
![image](https://user-images.githubusercontent.com/100116920/217053485-1e6de1f5-e9f1-4398-ac7a-0c94bdc91c47.png)

**Comment by fmunir1086** [comment]
timespent*03:15 February 06, 2023

Researched on setting inline images on Email, looks like we cannot set SVG and its explainable, we might need png or jpg of same icons and email will attach inline images and that Git hub issue will be resolved.

**Comment by ryansagot** [comment]
Hi @fmunir1086.

Please fix or apply the following:
1. Please update the "unikbase" beside the top logo to "Unikbase.
2. Put spaces/line between the sentences.
3. My selected language was English but received French email.

Thanks!

**Comment by fmunir1086** [comment]
timespent*01:00 February 10, 2023

Coordinated with Ryan for three points and truen out one is required to be worked on, done changes, comitted it on repo.

**Comment by ryansagot** [comment]
Language is implemented. User can change preferred language. Payment and notification email is in French. However, when user selects English in buytoken page, the payment page is in English but the notification is still in French. Will log a defect ticket in the future.
