### ISSUE TITLE
[Story] As a user I must receive a cancelled payment email notification.

### ISSUE THREAD

**Issue by ryansagot** [unikbase/mv-stripe#2]
<table dir="ltr" style="height: 538px;" border="1" cellspacing="0" cellpadding="0"><colgroup><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /></colgroup>
<tbody>
<tr><td><b/>
Goal/Request
 </td>
<td>
User must receive an email after cancelling payment through Stripe. Email content must vary based on the Profile Language.

https://www.notion.so/unikbase/Emails-Payment-stripe-35c8659b06f54eb19868609061921296
</td></tr>
<tr><td><b/>
Acceptance Criteria
 </td>
<td>

- As a user I must receive an email after a cancelled payment through Stripe.
- As a user I must receive the email in a language of my Profile Settings.

ENGLISH: 
Email Subject/Title: Your payment to Unikbase has been refused or cancelled
Email Content:
[unikbase logo]

We are sorry, but your payment has been refused or cancelled.

There may have been a problem with the payment information you provided, or your bank account may not have authorized the transaction.

Please check your bank account and credit card information and try again later. If the problem persists, please contact us for further assistance.

We will be happy to assist you.

The Unikbase Team

[Unikbase UU logotype]
+ Unikbase, 320 rue Saint-Honoré 75001 Paris, France 
Contact [[hello@unikbase.com](mailto:hello@unikbase.com)](mailto:hello@unikbase.com)

FRENCH:
Email Subject/Title: Votre paiement auprès d’Unikbase a été refusé ou annulé
Email Content:
[unikbase logo]

Nous sommes désolés, mais votre paiement a été refusé ou annulé.

Il se peut qu'il y ait eu un problème avec les informations de paiement que vous avez fournies, ou que votre compte bancaire n'ait pas autorisé la transaction.

Veuillez vérifier les informations de votre compte bancaire et de votre carte de crédit, et réessayer ultérieurement. Si le problème persiste, veuillez nous contacter pour plus d'assistance.

Nous restons à votre disposition.

L’équipe Unikbase

[Unikbase UU logotype]'
+ Unikbase, 320 rue Saint-Honoré 75001 Paris, France 
Contact [[hello@unikbase.com](mailto:hello@unikbase.com)](mailto:hello@unikbase.com)
</td></tr>
</tbody>
</table>

**Comment by fmunir1086** [comment]
timespent*02:10 January 25, 2023

endpoint created for failure case of stripe checkout and both updates checkout information's response and response code, tomorrow I will continue working on sending email notification for this case after updating corresponding entry of checkout

**Comment by fmunir1153** [comment]
timespent*02:00 January 26, 2023

Removed redundant logic for getting checkoutInfoUUId and replaced with mapped object to get that info and also Customer Email from stripe response
 - Added sending Success email logic for success case and unit tested webhook, that its working fine.
 - Tommorrow I will use locales to switch via French/English emails, do code clean up for endpoints and functions and will add images in email.

**Comment by fmunir1086** [comment]
timespent*03:25 January 30, 2023

Completed cancel url flow with Shehryar following same way of calling our endpoint form cancel Page as per @sebastien suggestion and verified response update for strip checkout entry record also the email.

**Comment by fmunir1086** [comment]
timespent*00:50 January 30, 2023

Communication/correspondence with different team members, added check to not send email in case user hits back button.

**Comment by ryansagot** [comment]
Language is implemented. User can change preferred language. Payment and notification email is in French. However, when user selects English in buytoken page, the payment page is in English but the notification is still in French. Will log a defect ticket in the future.
